### ISSUE TITLE
Any example image it can work on?

### ISSUE THREAD

**Issue by IlyaOvodov** [AEyeAlliance/web-application#1]
Respect for this project! I need such an application for my blind daughter studing, and it's an only opensource project on github I managed to find for this purpose!

Can you provide any example images it can work on? I tied to launch this web app on images from https://github.com/yeluo1994/DSBI dataset and got nothing more then "Translation: ," or somthing like this.

**Comment by IlyaOvodov** [comment]
A... Now I see, it can translate only one cropped line... Example is static/Emboss_cropped_pic.png

**Comment by tingyisu** [comment]
Hi, sorry for the late reply! 
Thanks so much for your support, I'm glad that you find our project useful :)
Yes, currently our model is only able to translate a cropped image of one line of Braille (it can be a sentence of Braille, but all the words need to be on one line) at a time. You can find more example images that our prototype works on here: https://github.com/HelenG123/aeye-alliance/tree/master/test . You could also try using your own cropped image (please refer to our tutorial page for more guidelines on how to crop your image). I hope that helps!
